name: docker_build_dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate tag
        id: gen_tag
        run: |
          TAG=$(printf '%(%Y%m%d%H%M%S)T\n' -1)
          echo '::set-output name=tag::'$TAG
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
              riazarbi/datasci-gui-gpu:${{ fromJson(steps.gen_tag.outputs.tag) }}-dev
              riazarbi/datasci-gui-gpu:focal-dev
